name: Add Labels
on:
  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/labeler
        name: Add labels
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
